---
title: "NCA_Analysis_and_Reporting_2019.rmd"
author: "Krina Mehta"
date: "8/27/2019"
output: html_document
---

```{r}
rm(list = ls())

#For some reason qpToolkit needs to be called before qpNCA, or crashes during NCA run (possible issue with mutate_cond)
library(qpToolkit)
library(qpNCA)
library(dplyr)
library(ggplot2)

#check package 1.0.17 or later is installed
packageVersion("qpNCA")
#[1] ‘1.0.20’
```

# Prep dataset
```{r}
head(Theoph)
print(plot(Theoph$conc~Theoph$Time))

#we need nominal time variable for some tasks.
NTAD <- c(0,0.3,0.5,1,2,4,5,7,9,12,24)
Theoph1 <- Theoph %>% 
  mutate(NTAD=metrumrg::snap(Time, NTAD)) %>%
  mutate(Subject=as.numeric(Subject)) %>%
  mutate(BLQ = ifelse(conc<0.15, 1, 0),
         LOQ = 0.15) %>%  #creating some BLQs
  mutate(conc = ifelse(BLQ==1, 0, conc),
         EXCL = 0) %>%
  as.data.frame() %>%
  arrange(Subject, Time)

cov= Theoph1 %>% mutate(Dose=as.numeric(Dose)) %>% select(Subject, Dose, Wt)  
#create a covariate dataset with one observation per curve; should also contain the variable with the dose amount (numerical)

```

# NCA Analysis
```{r}
NCAResults <- qpNCA(Theoph1, by=c("Subject"),
                    nomtimevar="NTAD", timevar="Time", depvar = "conc",
                    factor=1, reg="sd", route="EV", 
                    bloqvar="BLQ",  loqvar="LOQ", loqrule =1, excl= "EXCL",
                    includeCmax = "Y", timelab = "Time (hr)", 
                    deplab = "Concentrations (mg/L)", plotdir=NA, pdfdir=NA,
                    tau = NA, tstart = NA, tend = NA, teval = NA, 
                    cov = cov, dose = "Dose", ss = "N", method = 1)   

write.csv(NCAResults$pkpar, "nca_analysis_withwrapper_results.csv", row.names = F)

```

# First let's tabulate raw concentrations by nominal time and summarize
```{r}
Tab1 <- Listing.Sumstat.Conc(Theoph1, subjVar="Subject", timeVar="NTAD",
                             dvVar="conc", blqVar="BLQ", carryAlong="Dose", 
                             nsig=3, na.rm=TRUE)

print(kable(Tab1))
```

# Now, let's tabulate parameters in simuilar way
```{r}
datain = NCAResults$pkpar %>% distinct(., .keep_all = T)

# Select parmaters to be reported
keepers = Cs(Subject,tmax,cmax,tlast,auclast,aucinf.pred,cl.f.pred,
             vz.f.pred,thalf,no.points)

tabdat = datain %>% dplyr::select(keepers)

Tab2 <- Listing.Sumstat.Param(tabdat, subjVar="Subject", nsig=3, by=NULL,
                      vars_ignore=c("no.points"), 
                      keep=c("Subject","tmax","cmax","tlast","auclast",
                             "aucinf.pred","cl.f.pred",
                             "vz.f.pred","thalf"))

print(kable(Tab2))
```

