---
title: "nca_reporting_example.rmd"
output: html_document
author: "Krina Mehta"
---

#Install libraries
```{r, results='hide'}
rm(list = ls())
library(qpNCA)
library(qpToolkit)
qp.blue <- "#144A90"
qp.green <- "#4CB54F"
```

#Read datasets 
```{r}
#this is the dataset we used for NCA analysis
NTAD <- c(0,0.3,0.5,1,2,4,5,7,9,12,24)
Theoph1 <- Theoph %>% 
  mutate(NTAD=metrumrg::snap(Time, NTAD)) %>%
  mutate(Subject=as.numeric(as.character(Subject)), #converting from factor to numeric
         BQL = ifelse(conc<=0.25, 1, 0),                #just adding few BLQs to demonstrate functionality
         conc= ifelse(conc<=0.25, NA, conc))            #just adding few BLQs to demonstrate functionality
#this is nca analysis results file
dat <- read.csv("nca_analysis_results.csv", stringsAsFactors = F, na.strings = "NA")
```

#Tabulate concentrations vs time for each subject and calculate summary stats of concentrations per timepoint (can use visit instead of time)
```{r, results="markup", warnings=F}
ConcTab = nca.conc.table(Theoph1, 
                sumVar = "conc",         
                subjVar = "Subject",      
                timeVar = "NTAD",
                LOQ = 0.250,               #just adding to demonstrate functionality
                bloqCode = "BQL",    
                nsig=3) 

kable(ConcTab)
```

#Tabulate summary stats of concentrations per timepoint (can use visit instead of time) only
```{r, results="markup", warnings=F}
ConcSumTab = tapply(Theoph1$conc, Theoph1$NTAD, 
                   nca.sumstat.conc,
                   LOQ = 0.250,               
                   ns = 3,
                   bloqRule = "BLOQ=0",
                   oddCode = "M", 
                   bloqCode = "BLOQ") %>% 
              bind_cols()  #convert to data frame

#add names 
ConcSumTab1 <- cbind(Parameter = names(ConcSumTab$`0`), ConcSumTab)

kable(ConcSumTab1)
```

#Visualize NCA results
```{r,  results="markup", warnings=F}
plot<- left_join(Theoph1, dat) %>%
     ungroup() %>%
     mutate(TAD1=Time,
            DV=conc,
            start_conc=exp(intercept-lambda_z*start_th),
            end_conc=exp(intercept-lambda_z*end_th),
            thalf_txt=ifelse(!is.na(thalf),
            paste0("Half-life:",round(thalf,2)," h  "),"Half-life not calculated  "),
            radj_txt=ifelse(!is.na(thalf),
                            paste0("Adj. R-squared: ",round(r.squared,4),"  ")," ")) %>%
     group_by(Subject) %>%
     mutate(max_conc=10**(ceiling(log10(max(conc,na.rm=T)))),
            min_conc=10**(floor(log10(min(conc,na.rm=T))))) %>%
    ungroup() %>%
    filter(!is.na(DV))

plots = plot %>% group_by(Subject) %>% 
  
             do(plots=ggplot(data=.) +
                                
             geom_line(data=., mapping=aes(x=TAD1, y=DV), color=qp.blue) +

             geom_point(data=., mapping=aes(x=tmax, y=cmax), color="gold3", size=6) +

             geom_point(data=., mapping=aes(x=TAD1, y=DV), color=qp.blue, size=4) +
               
             geom_segment(data=.,x=.$start_th,xend=.$end_th,
                            y=log10(.$start_conc), yend=log10(.$end_conc),
                            color=qp.green, linetype="solid", size=1) +

             geom_point(data=.[.$TAD1>=.$start_th&.$TAD1<=.$end_th,], 
                         mapping=aes(x=TAD1, y=DV), size=4, color=qp.green) +

           annotate(geom="text",label=unique(.$thalf_txt), x=Inf, y=Inf, hjust=1, vjust=2) +

           annotate(geom="text",label=unique(.$radj_txt), x=Inf, y=Inf, hjust=1, vjust=4) +

           scale_y_log10(
            #limits=c(unique(.$min_conc),unique(.$max_conc)),
            #breaks=(10**(seq(log10(unique(.$min_conc)),log10(unique(.$max_conc))))),
            #labels=(10**(seq(log10(unique(.$min_conc)),log10(unique(.$max_conc)))))
                          ) + 
          xlab("Time after Dose (h)") +
          ylab("Concentrations (mg/L)") +
          theme(legend.direction="horizontal",legend.position="bottom", aspect.ratio=0.4,
                legend.text = element_text(size=15),
          plot.title =element_text(hjust = 0, size=15), 
          panel.background = element_rect(fill = 'white', colour="black"),
          panel.grid.major = element_line(colour = "grey"), 
          panel.grid.minor = element_blank(),
          axis.title.x = element_text(size=15), axis.title.y = element_text(size=15),
          axis.text.x=element_text(colour="black", size=15),
          axis.text.y=element_text(colour="black", size=15)) +
          ggtitle(paste0("Patient: ",.$Subject)))

print(plots$plots)

```

