globalVariables(c(
'cmax', # calc.ctmax
'time.lastall', # calc.par
'conc.lastall', # calc.par
'bloqvar1', # calc.par
'tlast', # calc.par
'aumcall', # calc.par
'aucall', # calc.par
'aumclast', # calc.par
'auclast', # calc.par
'time.tau', # calc.par
'conc.tau', # calc.par
'time.teval', # calc.par
'conc.teval', # calc.par
'time.part', # calc.par
'conc.part', # calc.par
'ptime', # calc.par
'firstmeast', # calc.par
'intercept', # calc.par.th
'lambda_z', # calc.par.th
'tlast', # calc.par.th
'auclast', # calc.par.th
'clast.obs', # calc.par.th
'clast.pred', # calc.par.th
'aumclast', # calc.par.th
'dosevar', # calc.par.th
'aucinf.obs', # calc.par.th
'auctau', # calc.par.th
'aucinf.pred', # calc.par.th
'aumcinf.obs', # calc.par.th
'aumctau', # calc.par.th
'tau', # calc.par.th
'aumcinf.pred', # calc.par.th
'mrtinf.obs', # calc.par.th
'cl.f.obs', # calc.par.th
'mrtinf.pred', # calc.par.th
'cl.f.pred', # calc.par.th
'area.back.extr', # calc.par.th
'vz.f.obs', # calc.par.th
'vz.f.pred', # calc.par.th
'cl.obs', # calc.par.th
'cl.ss', # calc.par.th
'cl.pred', # calc.par.th
'cl.f.ss', # calc.par.th
'no.points', # correct.conc
'intercept', # correct.conc
'r.squared', # correct.conc
'adj.r.squared', # correct.conc
'thalf', # correct.conc
'.', # correct.conc
'lambda_z', # correct.conc
'ptime', # correct.conc
'conc.tau', # correct.conc
't0val', # correct.conc
'applies.to.conc', # correct.conc
'lag.ctau', # correct.conc
'lead.ctau', # correct.conc
'lag.ttau', # correct.conc
'lead.ttau', # correct.conc
'time.tau', # correct.conc
'conc.part', # correct.conc
'lag.cpart', # correct.conc
'lead.cpart', # correct.conc
'lag.tpart', # correct.conc
'lead.tpart', # correct.conc
'conc.teval', # correct.conc
'lag.cteval', # correct.conc
'lead.cteval', # correct.conc
'lag.tteval', # correct.conc
'lead.tteval', # correct.conc
'conc.lastall', # correct.conc
'time.lastall', # correct.conc
'firstmeast', # correct.conc
'firstmeasc', # correct.conc
'lc1', # correct.conc
'lc2', # correct.conc
'back_extrap', # correct.conc
'lt1', # correct.conc
'lt2', # correct.conc
'tauval', # correct.conc
'timevar1', # correct.loq
'depvar1', # correct.loq
'bloqvar1', # correct.loq
'firstmeast', # correct.loq
'consecutive', # correct.loq
'loqvar1', # correct.loq
'no.points', # correct.time
'intercept', # correct.time
'r.squared', # correct.time
'adj.r.squared', # correct.time
'thalf', # correct.time
'.', # correct.time
'lambda_z', # correct.time
'ptime', # correct.time
'leaddv', # correct.time
'leadtime', # correct.time
'conc.tau', # correct.time
'applies.to.time', # correct.time
'lagdv', # correct.time
'lagtime', # correct.time
'conc.teval', # correct.time
'conc.part', # correct.time
'newdepvar', # correct.time
'no.points', # est.thalf
'adj.r.squared', # est.thalf
'lambda_z', # est.thalf
'sel', # est.thalf
'depvar', # lag_lead
'timevar', # lag_lead
'flag', # lag_lead
'ptime', # lag_lead
'.', # nca.sum
'intercept', # plot_reg
'lambda_z', # plot_reg
'start_th', # plot_reg
'end_th', # plot_reg
'thalf', # plot_reg
'adj.r.squared', # plot_reg
'cmax', # plot_reg
'.', # plot_reg
'tmax', # plot_reg
'.', # qpNCA
'loqrule.nr', # tab.corr
'loqrule.txt', # tab.corr
'create.nr', # tab.corr
'create.txt', # tab.corr
'trule.nr', # tab.corr
'trule.txt', # tab.corr
'applies.to.time', # tab.corr
'crule.nr', # tab.corr
'crule.txt', # tab.corr
'applies.to.conc', # tab.corr
'rule.nr', # tab.corr
'applies.to', # tab.corr
'rule.txt' # tab.corr
))
